/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFdsfArgs } from "./DeleteFdsfArgs";
import { FdsfFindManyArgs } from "./FdsfFindManyArgs";
import { FdsfFindUniqueArgs } from "./FdsfFindUniqueArgs";
import { Fdsf } from "./Fdsf";
import { FdsfService } from "../fdsf.service";

@graphql.Resolver(() => Fdsf)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FdsfResolverBase {
  constructor(
    protected readonly service: FdsfService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fdsf",
    action: "read",
    possession: "any",
  })
  async _fdsfsMeta(
    @graphql.Args() args: FdsfFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fdsf])
  @nestAccessControl.UseRoles({
    resource: "Fdsf",
    action: "read",
    possession: "any",
  })
  async fdsfs(@graphql.Args() args: FdsfFindManyArgs): Promise<Fdsf[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fdsf, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fdsf",
    action: "read",
    possession: "own",
  })
  async fdsf(@graphql.Args() args: FdsfFindUniqueArgs): Promise<Fdsf | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fdsf)
  @nestAccessControl.UseRoles({
    resource: "Fdsf",
    action: "delete",
    possession: "any",
  })
  async deleteFdsf(@graphql.Args() args: DeleteFdsfArgs): Promise<Fdsf | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
