/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteDasdArgs } from "./DeleteDasdArgs";
import { DasdFindManyArgs } from "./DasdFindManyArgs";
import { DasdFindUniqueArgs } from "./DasdFindUniqueArgs";
import { Dasd } from "./Dasd";
import { DasdService } from "../dasd.service";

@graphql.Resolver(() => Dasd)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DasdResolverBase {
  constructor(
    protected readonly service: DasdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Dasd",
    action: "read",
    possession: "any",
  })
  async _dasdsMeta(
    @graphql.Args() args: DasdFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Dasd])
  @nestAccessControl.UseRoles({
    resource: "Dasd",
    action: "read",
    possession: "any",
  })
  async dasds(@graphql.Args() args: DasdFindManyArgs): Promise<Dasd[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Dasd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Dasd",
    action: "read",
    possession: "own",
  })
  async dasd(@graphql.Args() args: DasdFindUniqueArgs): Promise<Dasd | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Dasd)
  @nestAccessControl.UseRoles({
    resource: "Dasd",
    action: "delete",
    possession: "any",
  })
  async deleteDasd(@graphql.Args() args: DeleteDasdArgs): Promise<Dasd | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
